### ISSUE TITLE
Please provide changelog in a web readable format 

### ISSUE THREAD

**Issue by aelmahmoudy** [metinkale38/prayer-times-android#100]
Currently the change log is provided in the code in HTML format. Yet it is not readable on the web, since github only views it only in raw format showing the HTML tags. Someone from the FDroid project told me that there are some services that render html from github repo content, but they all seem to need some setup.

**Comment by metinkale38** [comment]
you can now find them on https://github.com/metinkale38/prayer-times-android/tree/master/changelogs
