### ISSUE TITLE
some settings with long description are not readable and not understandable

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#101]
Hi,
some settings/options with long description are not readable and not understandable, because they end suddenly with "...". (for example in german language, i think in other language too)
For long descriptions its better to add a new line, for better readability and understandabilty!

Thank you very much, Great App !!

Best regards

**Comment by metinkale38** [comment]
Hi, 

could you give examples?
On my phone i do not have such problems, but it could be truncated on smaller displays...

Metin Kale

**Comment by jobbb** [comment]
![screenshot_2017-12-19-17-06-58 1](https://user-images.githubusercontent.com/23344828/34169537-a0603ecc-e4df-11e7-91b2-4bfe7e825c82.png)
