### ISSUE TITLE
Changing prayer times

### ISSUE THREAD

**Issue by shawn1thompson** [metinkale38/prayer-times-android#102]
My location is set to Hendricks County in Avon, IN, USA. I've noticed that the time for maghrib changes. If I open the app after clearing the cache and force stopping, the time is correct, but if I exit the app and open again without clearing the cache and stopping the app, the time is off by about half an hour. I haven't been able to verify this for other prayer times. I'm running Lineage OS 14.1 on a Nexus 6. If you require any further information, please let me know. Thank you.

**Comment by shawn1thompson** [comment]
I just verified the same issue with sunrise. It's off by about 15 minutes though. Also, synchronizing seems to have no effect. Thanks again.

**Comment by metinkale38** [comment]
I guess you are using the FDroid built right?

I will publish an update soon in Sha Allah...
