### ISSUE TITLE
problème chargement fichier csv

### ISSUE THREAD

**Issue by nobodyoone** [metinkale38/prayer-times-android#104]
Quand je veux charger les horaires pour ma localité, il n'y a pas d'horaire qui apparaît seulement des zéros.

**Comment by metinkale38** [comment]
you should use a CSV File like the following:

`2017-12-07; 11:11; 22:22; 33:33; 44:44; 55:55; 66:66` per line

it tries to recognize different formats and seperators, but like that it should work...
