### ISSUE TITLE
Problem with update to version 3.7 from f-droid

### ISSUE THREAD

**Issue by cron0mat** [metinkale38/prayer-times-android#106]
Selam alejkum,

previous version (3.6.6) from f-droid was working fine but update to 3.7 brought some problems :
* widget has disappeared 
* saved cities have disappeared

Phone is running LineageOS 14.1: 

Adding a new city leads to an exception  - here are some information from logcat:

`02-03 18:36:50.774  7928  7928 E RecentsTaskLoader: Unexpected null component name or activity info: ComponentInfo{com.metinkale.prayer/com.metinkale.prayerapp.vakit.MainStart}, null
02-03 18:36:50.774  7928  7928 E RecentsTaskLoader: Unexpected null component name or activity info: ComponentInfo{com.metinkale.prayer/com.metinkale.prayerapp.vakit.MainStart}, null
02-03 18:36:50.774  7928  7928 E RecentsTaskLoader: Unexpected null component name or activity info: ComponentInfo{com.metinkale.prayer/com.metinkale.prayerapp.vakit.MainStart}, null`

`02-03 18:37:06.039  5216  5216 E AndroidRuntime: FATAL EXCEPTION: main
02-03 18:37:06.039  5216  5216 E AndroidRuntime: Process: com.metinkale.prayer, PID: 5216
02-03 18:37:06.039  5216  5216 E AndroidRuntime: java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [long]
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at com.metinkale.prayerapp.vakit.times.b.l.a(WebTimes.java:87)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at com.metinkale.prayerapp.vakit.times.b.l.a(WebTimes.java:77)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at com.metinkale.prayerapp.vakit.fragments.SearchCityFragment.onItemClick(SearchCityFragment.java:227)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:4054)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: <init> [long]
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at java.lang.Class.getConstructor0(Class.java:2204)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at java.lang.Class.getConstructor(Class.java:1683)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	at com.metinkale.prayerapp.vakit.times.b.l.a(WebTimes.java:85)
02-03 18:37:06.039  5216  5216 E AndroidRuntime: 	... 13 more
02-03 18:37:06.041  2185 28412 W ActivityManager:   Force finishing activity com.metinkale.prayer/com.metinkale.prayerapp.MainActivity
02-03 18:37:06.051  5216  5216 I Process : Sending signal. PID: 5216 SIG: 9
02-03 18:37:06.102  2185  7927 I WindowManager: WIN DEATH: Window{f298784 u0 com.metinkale.prayer/com.metinkale.prayerapp.MainActivity}
02-03 18:37:06.102  2185  7322 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=54, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ], android.os.BinderProxy@3271d5d)
02-03 18:37:06.103  2185  7325 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=53, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ], android.os.BinderProxy@58806d2)
02-03 18:37:06.103  2185 18547 I ActivityManager: Process com.metinkale.prayer (pid 5216) has died`

**Comment by basilgohar** [comment]
I encounter the same or similar issue in Android 7.0 on an HTC 10.

**Comment by qwertyuser1983** [comment]
I think it related.

Constant crash in Advan i5E after the latest download via FDroid. :sob:

**Comment by qwertyuser1983** [comment]
I think it related.

Constant crash in Advan i5E after the latest download via FDroid. :sob:

**Comment by zmoliu** [comment]
I can't even add any city any more the app keeps crashing when i add a city to it.
Samsung A5 2016
Download via Fdroid

**Comment by awalis** [comment]
Same issue on Redmi Note 3 with LOS 14.1:
Crashes right on opening, and when it does open correctly, it crashes after manually selecting a city. I gave it all app permissions and privacy guard permissions.

Previous version (3.6.6) works fine though.
Thanks for the developers and community for this great job.

**Comment by devurandom** [comment]
Same issue on Fairphone FP2 with the Fairphone Open firmware 2018.03.1 and OpenGapps [pico](https://github.com/opengapps/opengapps/wiki/Pico-Package). Downgrading to 3.6.6 makes the issue no longer show up.

**Comment by metinkale38** [comment]
should be fixed with the last commit... an update will be released soon in sha allah

**Comment by devurandom** [comment]
@metinkale38 do you already have a scheduled date for the next release?

**Comment by devurandom** [comment]
Ramadan kareem! Could you please publish the next release soon? I think it would be useful for many people during this time.
