### ISSUE TITLE
Reset option crashes app after been selected.

### ISSUE THREAD

**Issue by abdul-qudus** [metinkale38/prayer-times-android#110]
#### Expected behavior
After making several counts, then selecting the reset option should clear all previous counts to default.

#### Actual behavior
After making counts then clicking on the reset option app crashes

#### How to reproduce
Download prayer times application on fdriod.
Open app, then from the slide on the menu option select ''dhikr''. 
Make several counts on the round counter displayed on the screen, then click on the reset option below it by the left. 
App crashes instantly.

* Application: prayer times, version 3.7, version 3.7. Fdriod
* Operating system: andriod 7.0 nougat. Tecno wx3p

#### Recording Of The Bug
![videotogif_2018.03.14_22.54.30.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521065568/keltugasd2i904kpv20s.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@abdulqudus/reset-option-crashes-app-after-been-selected">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by metinkale38** [comment]
thank you, will be fixed with the next release in sha Allah
