### ISSUE TITLE
bug found when try to back up data in prayer times app

### ISSUE THREAD

**Issue by muhammadarif1** [metinkale38/prayer-times-android#111]
#### Expected behavior
should be when users use the feature to back up users can backup data to stay safe if not accidentally lost

#### Actual behavior
when I try to use this back up feature to store my important data this app just crashes and stops just like that
#### How to reproduce
- download prayer time app
- open the app
- go to setting and chose option to back up and the app will gwt crased

* Operating system: android lolipop 5.1 idos advan s5e nxt
app verion;  prayer time v3.7
#### Recording Of The Bug
https://youtu.be/W2KounAvNv0

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@muhammadarif/bug-found-when-try-to-back-up-data-in-prayer-times-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by metinkale38** [comment]
fixed
