### ISSUE TITLE
bug found when try to add prayer schedule

### ISSUE THREAD

**Issue by muhammadarif1** [metinkale38/prayer-times-android#112]
#### Expected behavior
the application allows users to add their prayer schedule and activate the automatic location
#### Actual behavior
when I try to add my prayer schedule and activate the automatic location of this application even crashes and stops
#### How to reproduce
-download prayer time app v 3.7
- open the app
- clik + symbol
- enable automatic location adn the app  will crashed

* Operating system: android 5.1 idos advan s5e nxt
app version   : prayer time v 3.7

#### Recording Of The Bug
https://youtu.be/7xZqKPAPhBA

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@muhammadarif/bug-found-when-try-to-add-prayer-schedule">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by metinkale38** [comment]
should be fixed already
