### ISSUE TITLE
Prayer Times App crashes when trying to export a prayer time

### ISSUE THREAD

**Issue by Godwyyn** [metinkale38/prayer-times-android#114]
#### Expected behavior
When trying to export a prayer time either as CSV or PDF without selecting or changing the date, I expected the app to export the prayer time when I click on done or present a toast or dialog asking me to select the date before clicking on done.

#### Actual behavior
When I clicked on Export, and choose either CSV or PDF and clicked on Done without changing or selecting the date, the app crashes.

#### How to reproduce
- Download the Prayer Times app
- Launch the app
- At the Prayer Time Activity,click on the Fab icon to add a prayer time
- After adding a prayer time,from the list of prayer times selcect a prayer time
- At the prayer times item Activity click on the menu icon after notification icon to see the drop down  options
- Click on export
- Click on CSV or PDF
- From the date selection dialog  click on done without changing the date
- The app crashes and Exit

* Version: Prayer Times version 3.6.5

* Operating system: Infinix hot:Android Kitkat

#### Recording Of The Bug
https://www.youtube.com/watch?v=Zsk4IM91Omc
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@godwyn/prayer-times-app-crashes-when-trying-to-export-a-prayer-time">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by metinkale38** [comment]
should be fixed with the next update in sha allah
