### ISSUE TITLE
AWESOME LOGO DESIGN FREE FOR YOU 

### ISSUE THREAD

**Issue by abdulmalikkhan655** [metinkale38/prayer-times-android#118]
Hello, @metinkale38I want to contribute in "prayer-times-android" so i  want to designed a new logo for "prayer-times-android" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
https://www.facebook.com/abdulmalikkhan655

**Comment by metinkale38** [comment]
thank you, i think the current icon is fine (also i made some modifications to fit better with new android versions)

I am open for suggestions and new icons, but i cannot promise i will take them, so if you want to create an new logo, you can do it, but do not expect me to use it. I might do or might not.
