### ISSUE TITLE
How you are reducing the apk size its almost 22Mb?In playstore it shows 6Mb

### ISSUE THREAD

**Issue by Rafiqgithub** [metinkale38/prayer-times-android#131]

**Comment by metinkale38** [comment]
1) Debugging APK contains more stuff (not proguarded, debug information etc)
2) Google Play Splits the APK to multiple APKs to reduce the size. Each phone will get a trimmed down version of the App (you have to configure it, or do it manually)
3) It is probably downloaded compressed
