### ISSUE TITLE
İmsakiye sadece bir aylık 

### ISSUE THREAD

**Issue by bakiince** [metinkale38/prayer-times-android#132]
İmsakiye sadece bir aylık gösteriyor. Bir aydan daha ileri tarihli namaz vakitleri 00:00 olarak gözüküyor. Bazen otomatik yenileme yapmıyor. Bir ay boyunca yenileme yapılmazsa saat 00:00 da namaz vakti gibi uyarı veriyor, ezan okuyor. Namaz vakitleri güncellemesini uygulamada neyin tetiklediğini çözemedim. Namaz vakitleri diyanet'ten alındığında oluyor galiba.

**Comment by metinkale38** [comment]
Diyanetin Internet Sayfasında sadece 30 Günlük veriler olduğundan dolayı Uygulamaya fazlasını indiremiyorum malesef. Başka Takvimlerde daha uzun süre de olabilir.

Vakitlerin indirilmesi için Menü'den Güncellemeye basabilirsiniz...
