### ISSUE TITLE
Add new prayer times calculation method for France

### ISSUE THREAD

**Issue by crazybusta94** [metinkale38/prayer-times-android#134]
Please can you add a special prayer time calculation method for France, UOIF - Union des organisations islamiques de France ?

**Comment by nicolas-raoul** [comment]
http://www.uoif-online.com/pourquoi-le-12eme-degre-de-latitude-pour-determiner-lhoraire-du-ichaa-du-soubh/

**Comment by metinkale38** [comment]
(Link above is dead, see here: http://web.archive.org/web/20190330130629/http://www.uoif-online.com/nos-associations/)

12 Degrees seem to be similiar to the times of DITIB and IGMG (CIMG in France), seems that old calculations the islamic world use to use do not work for Europe (or at least higher latitudes). almost all large islamic organizations tend to go another way...

Currently you can simply add the times for UOIF yourself by selecting Calculated Prayer Times and settings 12 Degrees for Fajr and Ishaa, but i will add UOIF in one of the next releases as custom calculation method...
