### ISSUE TITLE
[prayer-times-android 3.7.3] The share button is not working properly

### ISSUE THREAD

**Issue by XAMIR555** [metinkale38/prayer-times-android#136]
#### Project Information
* Repository----------------:[Here](https://github.com/metinkale38/prayer-times-android)
* Project Name------------:  [prayer-times-android](https://play.google.com/store/apps/details?id=com.metinkale.prayer)
* Publisher-------------------:[Metin Kale metinkale38](https://github.com/metinkale38)
* My GitHub account------:  [Here](https://github.com/XAMIR555)

#### Expected behavior
When I click on the share button, different options should appear next to where I can share it

#### Actual behavior

When I click on the share button, no options appear as you can see in the video

#### How to reproduce
* [download ](https://play.google.com/store/apps/details?id=com.metinkale.prayer)and open the application 
* At the top left click on the 3 horizontal  lines
* click on Sahih al-Bukhary
* At the top right click on the three vertical line
* click on share 
* Note the Bug
* Browser/App version-: 3.7.3
* Operating system----: 9.0.0

#### Recording Of The Bug
-![20190507_165549.gif](https://ipfs.busy.org/ipfs/QmWq38svRqV1j8zQnchNUVKF8xT39CKkxZCibfiTCjGrJ2)

**Comment by XAMIR555** [comment]
sir @metinkale38 review My post

**Comment by metinkale38** [comment]
thank you for reporting, the issue will be inshaAllah fixed with the next update...
