### ISSUE TITLE
When you will release newest version for fdroid? Only Version 3.7 (193) is available?

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#138]
When you will release newest version for fdroid? Only Version 3.7 (193) is available with some bugs. Version 3.6.6 is recommended for Fdroid.

Best regards

**Comment by fazlerabbi37** [comment]
@jobb I see a new version has been released with `fdroid` tag in the GitHub on Apr 19, 2020. The F-Droid metadata has been updated [here](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.metinkale.prayer.yml). It will take some time to for F-Droid to build it, so we need to be patience a bit. :smile:

**Comment by metinkale38** [comment]
Actually i did some effort to update the F-Droid Build as @fazlerabbi37 mentioned..

I don't know, whether there are issues in my configuration or F-Droid is simply taking so long to build all apps,

If somebody knows more about that, any help is welcome...

**Comment by fazlerabbi37** [comment]
3.7.4 was added to F-Droid on May 6, 2020.
