### ISSUE TITLE
Elle konum ekleme seçeneği

### ISSUE THREAD

**Issue by yasarciv67** [metinkale38/prayer-times-android#139]
Merhabalar. 3.7.3 sürümünden önce il ve ilçe bazında konum ekleyebiliyordum. Ancak bu sürümde kaldırılmış. Arama düğmesinden bulunduğum ilçeyi bulamıyorum. Gps kullanmak da istemiyorum.

**Comment by metinkale38** [comment]
Selamun aleyküm, 

aşağıda "Şehri elle seç" özelliği var, buradan eskisi gibi aynı şekilde konum ekleyebilirsiniz...
