### ISSUE TITLE
Dahili bildirim sesi hatası

### ISSUE THREAD

**Issue by yasarciv67** [metinkale38/prayer-times-android#140]
Bildirim seslerinde Diğer düğmesini kullanarak telefonun dahili seslerinden birini seçip Tamam dediğimde "Namaz Vakti Durdu" uyarısı verip kapanıyor.

**Comment by herbap** [comment]
Bildirim ses ayarını; Bildirim, zil veya alarm olarak ayarlamaya çalıştığında ses çalmıyor (sadece Media veya manual ses seviyesi seçince çalıyor)

**Comment by metinkale38** [comment]
her iki sorun Play Store'da yayınlanmış son sürüm ile giderildi inşaAllah...
Bildirdiğiniz için teşekkür ederim
