### ISSUE TITLE
Unexpected behaviours after a screen orientation change (reported by activity)

### ISSUE THREAD

**Issue by dlicse1** [metinkale38/prayer-times-android#144]
I developed an automatic test case generation tool and it detected these problems in your app.
I would like to know if you consider them as failures and, if not, why. Thanks for your collaboration.

1) When I change the orientation of the device screen, QiblaDirection activty changes the "compass" icon
![2019-07-28 16-41-00_before](https://user-images.githubusercontent.com/53469180/62204361-5cc9cb00-b38d-11e9-9ee5-5ec1a4e67861.png)
![2019-07-28 16-41-00_after](https://user-images.githubusercontent.com/53469180/62204362-5cc9cb00-b38d-11e9-973e-84b297a8d44b.png)

2) When I change the orientation of the device screen, EditLocation activity doesn't keep the scroll position
![2019-07-28 15-43-21_before](https://user-images.githubusercontent.com/53469180/62204241-1ffdd400-b38d-11e9-95e7-ee21b9e7a936.png)
![2019-07-28 15-43-21_after](https://user-images.githubusercontent.com/53469180/62204243-1ffdd400-b38d-11e9-8b51-d636a1208c0f.png)

**Comment by metinkale38** [comment]
these screenshots do not refer to my app. Its another app.

**Comment by dlicse1** [comment]
I'm sorry, I've downloaded your app from the Google Play Store (this time, I'm sure it's yours) and I performed the same analysis. I report here the results even if the issue has been closed yet. Could you give me a quick feedback about the problems I found? It's for research purposes. Thank you in advance!

I developed an automatic test case generation tool and it detected these problems in your app.
I would like to know if you consider them as failures and, if not, why. Thanks for your collaboration.

1) When I change the orientation of the device screen, MainActivity changes its state. Below there are three different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The current page switches to the selecting language one
![2019-08-10 18-15-49_before](https://user-images.githubusercontent.com/53818789/62832384-6ffe5580-bc2d-11e9-89c2-b09222955a92.png)
![2019-08-10 18-15-49_after](https://user-images.githubusercontent.com/53818789/62832385-6ffe5580-bc2d-11e9-89b2-495101fb1836.png)

-- second case --
The current page changes
![2019-08-10 18-21-38_before](https://user-images.githubusercontent.com/53818789/62832390-7f7d9e80-bc2d-11e9-8bf5-6c1ed02ec888.png)
![2019-08-10 18-21-38_after](https://user-images.githubusercontent.com/53818789/62832391-80163500-bc2d-11e9-89fb-375137fc9d1e.png)

-- third case --
It doesn't keep the scroll position
![2019-08-10 20-36-07_before](https://user-images.githubusercontent.com/53818789/62832399-a76d0200-bc2d-11e9-8f08-a5459e30c663.png)
![2019-08-10 20-36-07_after](https://user-images.githubusercontent.com/53818789/62832400-a76d0200-bc2d-11e9-9f57-d804500689b5.png)

**Comment by metinkale38** [comment]
The first two issues seem wrong, and i could'nt reproduce the...

Case 1:
Could'nt reproduce at all.
The first screenshot is the main screen, and the second screen is the tutorial, which is shown once before the main screen and the tutorial is also portrait only...

Case 2:
This screen is not rotatable and portrait only. The "state change" is not due to orientation change, it is because an animation, which is shown at that screen.

Case 3:
Yes, scroll position is not saved, which i think, is not really an issue...
