### ISSUE TITLE
Bildirim sesi

### ISSUE THREAD

**Issue by yasarciv67** [metinkale38/prayer-times-android#147]
Uygulamada bildirim sesi ayarını Ses seviyesi seçin olarak ayarladığımda telefonu sessize veya titreşime aldığımda yinede ses çalmaya devam ediyor. Bu durum olağan mıdır?

**Comment by ahmedeltaher** [comment]
please English, I couldn't understand you well.

**Comment by yasarciv67** [comment]
Excuse me. If I set the notification sound in the application to Select volume, the phone continues to play sound even if it is muted or vibrated.  Is this usual?

**Comment by metinkale38** [comment]
@yasarciv67 evet, bu normaldir.

Eğer "Ses Seviyesi seç" ayarını kullanırsanız, o sesde okunacaktır, telefon sessizde olsa dahi.

Eğer sessizde okunmamasını istiyorsanız, Ses Seviyesini Zil veya Bildirim Sesine bağlı olarak ayarlamanız gerekir.

@ahmedeltaher thank you for trying to help :)
