### ISSUE TITLE
Kalıcı notificasion

### ISSUE THREAD

**Issue by Burak421** [metinkale38/prayer-times-android#148]
Selamlar, kalıcı notificasion bazen durup dururken hollandacaya dönüyor. Sonra tekrar bir müddet sonra Türkçe'ye geri dönüyor.

Bu hatayı bildirmek istedim, teşekkürler.

**Comment by Burak421** [comment]
![Screenshot_20191128-203624_Prayer Times](https://user-images.githubusercontent.com/57795979/69829081-db8d2280-121e-11ea-9c75-7529998ba843.jpg)

**Comment by Burak421** [comment]
Sonra Namaz Vakti programını açtığımda geri Türkçe'ye dönüyor.
![Screenshot_20191128-203726_Samsung Internet](https://user-images.githubusercontent.com/57795979/69829108-0bd4c100-121f-11ea-8b3a-56581b5e1e51.jpg)

**Comment by Burak421** [comment]
![Screenshot_20191201-135303_Prayer Times](https://user-images.githubusercontent.com/57795979/69914231-073c2280-1442-11ea-88b8-d145e5723d31.jpg)

**Comment by Burak421** [comment]
Türkçe kalmıyor

**Comment by metinkale38** [comment]
bu sorun çihazdan çihaza değişebiliyor.

Normalde tüm Uygulamalar Telefonun System Dili ile çalışıyor, fakat Namaz Vakti Uygulaması kendi dil seçme özelliği sunuyor. Bazı Telefonlarda malesef sorun oluyor, ama sürekli olarak düzeltmeye çalışıyoruz inşaAllah
