### ISSUE TITLE
Diyanet Konum Hesaplama

### ISSUE THREAD

**Issue by utrucceh** [metinkale38/prayer-times-android#149]
Merhabalar,

Diyanet, IlceBilgisiDetay2Response metodu ile aşağıdaki bilgileri dönderiyor ancak, enlem boylam bilgisi döndermiyor, kod içerisinde bunu hesaplayabilen bir metod varmıdır, yada örnek kod paylaşabilirmisiniz. 
Amacım uygulama içerisinde konumu locationListener üzerinden değilde, direk data üzerinden çekebilmek.
Teşekkürler

            <a:CografiKibleAcisi>164</a:CografiKibleAcisi>
            <a:IlceAdi>ADANA</a:IlceAdi>
            <a:IlceAdiEn i:nil="true"/>
            <a:IlceID>9146</a:IlceID>
            <a:KabeyeUzaklik>1784</a:KabeyeUzaklik>
            <a:KibleAcisi>160</a:KibleAcisi>
            <a:SehirAdi>ADANA</a:SehirAdi>
            <a:SehirAdiEn i:nil="true"/>
            <a:SehirID>500</a:SehirID>
            <a:UlkeAdi>TÜRKİYE</a:UlkeAdi>
            <a:UlkeAdiEn i:nil="true"/>
            <a:UlkeID>2</a:UlkeID>

**Comment by metinkale38** [comment]
Selamun aleyküm,


Tam olarak ney yapmak istediğinizi bilmiyorum, ama şu dosyalara bakarsanız,
belki işinize yarar:
https://github.com/metinkale38/prayer-times-android/blob/master/features/times/src/main/res/raw/diyanet.tsv

https://github.com/metinkale38/prayer-times-android/blob/master/features/times/src/main/java/com/metinkale/prayer/times/times/Cities.java

Ayrıca burda
https://github.com/metinkale38/prayer-times-android/blob/master/features/times/src/main/java/com/metinkale/prayer/times/times/TimesBase.java

görüldüğü gibi, eklenen tüm şehirlere enlem boylam (lat, lng) bilgileri
zaaten ekleniyor, yani mevcut şehirlerden çıkartabilirsiniz.



utrucceh <notifications@github.com> schrieb am So., 9. Feb. 2020, 21:48:

**Comment by utrucceh** [comment]
Aleykum Esselem,
Öncelikle geri dönüşünüz için teşekkür ederim.
Belirtmiş olduğunuz kodlarda şehir ismi üzerinden arama yapılarak yapılıyor.
Amacım internete gerek kalmaksızın, aşağıdaki üç bileşen ile konumu hesaplatmak:

-  kıblenin konumu
-  kıbleye olan açı
-  kıbleye olan mesafe

**Comment by metinkale38** [comment]
Gerekli hesaplamaları burda bulabilirsiniz:

https://github.com/metinkale38/prayer-times-android/blob/master/features/compass/src/main/java/com/metinkale/prayer/compass/MainFragment.java
