### ISSUE TITLE
İgmg namaz vakitleri gostermiyor 

### ISSUE THREAD

**Issue by Musab20** [metinkale38/prayer-times-android#151]
Selamun aleykum 
Öncelikle bu güzel uygulamanızdan dolayı çok teşekkür ediyorum 
İslam toplumu milli görüş teşkilatımızın hazırladığı namaz vakitleri uygulamanizda göremiyoruz yani 0 lar olarak gösteriyor 
Bildirmek istedim inşAllah en kısa zamanda düzeltme gelir bizde bu güzelim uygulamadan istifade etmeye devam ederiz 
Kolay gelsin 
Selametle 
Musab

**Comment by metinkale38** [comment]
Aleyküm selam, 
29. Şubat dolayısıyla tek günlük bir sorundu, şimdi çalışıyor
