### ISSUE TITLE
3.7 crash GrapheneOS

### ISSUE THREAD

**Issue by Aurelius5** [metinkale38/prayer-times-android#154]
Hi there, I hope to bring some good contribution to the table. 

As I try to select my location from the entry menu, the application just closes altogether and return to the app launcher.
It also happens when I try to change the colors inside the Dhikr menu.

I tried uninstalling and reinstalling a bunch of times, but to success.

I'm running version 3.7 of the app, downloaded from F-droid, on a Pixel 3A running GrapheneOS 2020.05.05.02 

https://github.com/GrapheneOS/platform_manifest/releases/tag/QQ2A.200501.001.B2.2020.05.05.02

If anything else is needed, I'm ready to support.

**Comment by metinkale38** [comment]
Hi, think the issue is related to #138 

Your Version is a bit outdated, these issues should be fixed in latest play store version, but somehow i did not manage to update the F-Droid build...
