### ISSUE TITLE
Last digit missing?

### ISSUE THREAD

**Issue by kaitou1412** [metinkale38/prayer-times-android#155]
Please check the image below
Last digit in minute missing?
For example 11:54 showed up as 11:5
I think it's because the font gets bold format

(The first notification is from QuranBest, the second notification is from Prayer Times Android)
![IMG-20200604-WA0001](https://user-images.githubusercontent.com/5919461/83741456-6ba29d80-a682-11ea-9110-5fadfbd2f145.jpg)

**Comment by metinkale38** [comment]
will be fixed in next update in sha allah
