### ISSUE TITLE
abric api key issue

### ISSUE THREAD

**Issue by tufeeqsaeed** [metinkale38/prayer-times-android#161]
Could not get unknown property 'FabricApiKey' for ProductFlavor_Decorated{name=play, dimension=store, minSdkVersion=null, targetSdkVersion=null, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=null, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor.

i have tried to build code but had faced this error. how to fix it?

**Comment by metinkale38** [comment]
create a gradle.properties file with following contents:

`GoogleApiKey=<YOUR_GOOGLE_API_KEY>
FabricApiKey=<YOUR_FABRIC_API_KEY>`

These are private api keys, thats why i did not included them into the project
