### ISSUE TITLE
Tesbihat

### ISSUE THREAD

**Issue by mustafakilic** [metinkale38/prayer-times-android#162]
Selamun aleykum.
Tesbihatın dua, salavat ve ayetlerini arabca yazabilir misiniz? Malumunuz, latin harflerle tam ses ve telafuz verilemiyor.
 
Bir diğer ricam eğer mümkünse, kıble saati içinde güneşin konumuna göre kıbleyi buluyoruz. Buraya birde geceleri Ay'a göre kıble tayini eklenebilir mi?

Allah kolaylıklar versin.
Vesselam.

**Comment by metinkale38** [comment]
Aleyküm selam,

Uygulamadakı Tesbihatın aynısını arapca olarak aramıştım ama tamamı ile bulamamıştım malesef...

Ay'a göre kıble tayını zannımca o kadar kolay olmayacak, Günesi hesaplama için internetde birçok yöntem bulunuyor
