### ISSUE TITLE
Notification Bar Dark mode Text Color

### ISSUE THREAD

**Issue by NuriNP** [metinkale38/prayer-times-android#163]
Selamun Aleykum.
The Notification bar in Dark mode is not easy to read because bouth the text and the background is black. Please Change the Text Color to White.
Thank you.
Nuri

**Comment by metinkale38** [comment]
Alaikum salam, 
Unfortunately Notification Color handling is different on each Phone Brand, so it was not possible to find a unique way of solving it.

In the Application Settings you can configure the Notification Colors....
