### ISSUE TITLE
doesn't work: permanent notification - show minutes

### ISSUE THREAD

**Issue by frknltrk** [metinkale38/prayer-times-android#166]
i can't see how many minutes left to the next prayer in the status bar even though the related option in the settings is turned on.
bir kere başarmıştım ama nasıl yapmıştım ben de bilmiyorum. format attıktan sonra bir türlü açamadım o **kalan dakika** göstergesini.

**Comment by metinkale38** [comment]
"Kalici Notification" ayarı acık olması lazım (Vakit ekranında yukarıda Saat Simgesine basınca açılıyor)

**Comment by frknltrk** [comment]
> "Kalici Notification" ayarı acık olması lazım (Vakit ekranında yukarıda Saat Simgesine basınca açılıyor)

sonrada çözdüm ama konuyu kapatmayı unutmuşum. teşekkürler :)
