### ISSUE TITLE
İgmg Hollanda Hoogezand

### ISSUE THREAD

**Issue by Hamsat42** [metinkale38/prayer-times-android#168]
Slm Metin kardesim
1 Aralik itibariyle bütün vakitler 00:00 güncelleme de yapmiyor , evde 4 telefonda yuklu hepsi ayni 
Kolay gelsin

**Comment by gmipf** [comment]
Slm, IGMG bende de aynisi, hepsi 00:00, Almanya Hamburg.

**Comment by Hamsat42** [comment]
Metin kale update yapmış,, google update i sunmasını bekliyoruz

**Comment by RealTago** [comment]
Selamunaleykum,

IGMG Genel olarak çalışmıyor. Bütün vakitler 00:00.

**Comment by gmipf** [comment]
Update cikti, calisiyor yine.

**Comment by Hamsat42** [comment]
> Selamunaleykum,
> 
> IGMG Genel olarak çalışmıyor. Bütün vakitler 00:00.

Update yapin igmg internette vakit yerlerini degistirdigi icin olmuyormuş , simdi tekrar calisiyor
