### ISSUE TITLE
How to Obtain IGMGApiKey

### ISSUE THREAD

**Issue by binayakumar09** [metinkale38/prayer-times-android#173]
The compilation fails for IGMGApiKey. Can you please help to understand how to register for this key. Could not get much info from the web. Thank You :)

**Comment by metinkale38** [comment]
I got the IGMGApiKey personally from IGMG. it is not a public API, therefore it is not possible to obtain a key. 

If you plan to fork this App, unfortunately you cant use the IGMG Times.
