### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by necaticetinkaya** [metinkale38/prayer-times-android#183]
Diyanet vakit saatlerini indirmiyor

**Comment by yerbakili** [comment]
Sorun bugunku guncelleme ile de cozulmedi.

**Comment by metinkale38** [comment]
son güncelleme ile sorun giderilmiş olması gerekiyor, bende oluyor şuanda. eğer halen olmuyorsa, tekrardan açabilirsiniz.
