### ISSUE TITLE
Add Option to make next prayer bold instead of current one in Notification Widget

### ISSUE THREAD

**Issue by Berki2021** [metinkale38/prayer-times-android#184]
Currently, it is so, that the current prayer is bold (highlighted) in the notification tray. I would love to see an option in which you can change this behavior and set the next upcoming prayer as highlighted:

### Current (fajr being the next prayer)

![grafik](https://user-images.githubusercontent.com/65120636/141147611-a3e7a509-1dc0-4793-be80-9f800126335e.png)

### Wanted

![grafik](https://user-images.githubusercontent.com/65120636/141147854-a4e6ef15-70a9-4c29-93de-02f5ab73a3b0.png)

**Comment by metinkale38** [comment]
You can already do that. Check the App Settings, there is a setting called "Prayertime Indicator"
