### ISSUE TITLE
Need some information/instructions on API setup

### ISSUE THREAD

**Issue by javedmoon** [metinkale38/prayer-times-android#202]
Hi,
I have downloaded the code and when trying to build the app the google Api and the IGMP Api doesnt work. 
Even if i remove the compass function and skipp the Google api in settings.gradle and move forwared the time function generates the error as IGMP Api is missing.
How can i obtain the IGMP API and get the timetable function working please ?

**Comment by javedmoon** [comment]
i get the following error
A problem occurred evaluating project ':features:times'.

> Could not get unknown property 'IGMGApiKey' for DefaultConfig$AgpDecorated_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=23, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=33, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=1.0, applicationId=null, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=SigningConfig$AgpDecorated_Decorated{name=debug, storeFile=C:\Users\asdasd\.android\debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=pkcs12, v1SigningEnabled=true, v2SigningEnabled=true, enableV1Signing=null, enableV2Signing=null, enableV3Signing=null, enableV4Signing=null}, resConfig=[], buildConfigFields={}, resValues={}, proguardFiles=[], consumerProguardFiles=[], manifestPlaceholders={}, wearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig$AgpDecorated.

**Comment by javedmoon** [comment]
if i by pass the above feature then after resolving all the issues i get the following

Execution failed for task ':app:checkFdroidDebugAarMetadata'.
> Could not resolve all files for configuration ':app:fdroidDebugRuntimeClasspath'.
   > Could not find dev.metinkale.prayertimes:core:1.0-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/dev/metinkale/prayertimes/core/1.0-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/dev/metinkale/prayertimes/core/1.0-SNAPSHOT/core-1.0-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/dev/metinkale/prayertimes/core/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/dev/metinkale/prayertimes/core/1.0-SNAPSHOT/core-1.0-SNAPSHOT.pom
       - file:/C:/Users/asd/.m2/repository/dev/metinkale/prayertimes/core/1.0-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/asd/.m2/repository/dev/metinkale/prayertimes/core/1.0-SNAPSHOT/core-1.0-SNAPSHOT.pom
     Required by:
         project :app > project :features:times

**Comment by binayakumar09** [comment]
Anyone was able to figure out how to fix this issue? I am also facing the same.

**Comment by metinkale38** [comment]
I got the IGMGAPi key with private contacts, normally you do not get it, so you would have to remove IGMG Supports.

It's not a problem btw, because as of 01.01.2023 they share the same calculation as Diyanet, I might also remove one of them at some time.

**Comment by binayakumar09** [comment]
> I got the IGMGAPi key with private contacts, normally you do not get it, so you would have to remove IGMG Supports.
> 
> It's not a problem btw, because as of 01.01.2023 they share the same calculation as Diyanet, I might also remove one of them at some time.

Thank You so much for your response. There is another issue that we are facing as mentioned in earlier issue - 
Could not find dev.metinkale.prayertimes:core:1.0-SNAPSHOT.
Can you please help with that.

**Comment by metinkale38** [comment]
You have to checkout https://github.com/metinkale38/open-prayer-times an call publishToMavenLocal. It is currently not deployed in a Maven Repository.

**Comment by hayalolsam** [comment]
open prayer times veya eski maven 0.9.3 ile denedim bir türlü çalıştırmadım. Bir çok yazılımı kurup direk sync edince ayar yapmadan build apk alabiliyordum bunda bir türlü alamadım. https://repo.huaweicloud.com/repository/maven/org/metinkale/praytimes/0.9.3/  
direk tek tık build alabileceğimiz bir link atma şansınız var mıdır?

**Comment by metinkale38** [comment]
https://repo.huaweicloud.com/repository/maven/org/metinkale/praytimes/0.9.3/ is old and not used anymore.

i added following files:
https://github.com/metinkale38/prayer-times-android/blob/master/BUILD_INSTRUCTIONS.md
https://github.com/metinkale38/prayer-times-android/blob/master/ci_build.sh

these should help to build the applicaton
