### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by telip007** [metinkale38/prayer-times-android#45]
I'm trying to code a skill for amazon echo to say the next prayer times but I'm struggling to find a service to get prayer times from diyanet, could you help me ?

**Comment by metinkale38** [comment]
Look inside the "com/metinkale/prayerapp/vakit/times" package there you will find everything 

with Other.Cities you can search for cities and get their id's 
The time provider (e.g. Diyanet) is encoded to the ID. 
Then you have to use the WebTimes class and add the city
(you can also do the above in the ui) 

Then you can use the times class to get all time calendars and for example call getTimes() to get the times for a specific day. 

If you have more questions just ask...
