### ISSUE TITLE
bug in "use arabic prayer times"

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#47]
If i set the "use arabic prayer times" option, the prayer time was changed.
But if i uncheck "use arabic prayer times" option, the prayer time will not changed back.

**Comment by metinkale38** [comment]
I can't reproduce this bug, but i got a few mails, where users have the same problem. 

Do you also have that problem with the language or only the "Arabic prayer times" option?

**Comment by jobbb** [comment]
I use the german language and i had the problem with "Arabic prayer times" option only.
(Please can you generally describe me, what is the difference with arabic prayer times and without.)
