### ISSUE TITLE
new Prayer times calculation method

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#49]
Please can you add a special prayer time calculation method for Morocco, Ministry of Endowments and Islamic Affairs. I used this in my prayertimes app named "Salatuk". If i use the Egypt-Method, from time to time i must adjust the prayertimes.

**Comment by metinkale38** [comment]
Is there a official website, where the prayertimes for all cities are listed (or a provided calculation formula)?

**Comment by jobbb** [comment]
http://www.habous.gov.ma/fr/

**Comment by jobbb** [comment]
Thank you! I'am waiting for your next release version in F-Droid!
