### ISSUE TITLE
gps compass option

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#50]
Some Android phones do not have a magnetic compass inside. They must use GPS.
<br />Is it possible to integrate a option for an GPS-Compass, if it's easy to integrate this?
<br />Best regards

**Comment by metinkale38** [comment]
For phones without a magnetic compass there is the map view, where you can see the direction on the map. 

As far i know apps like Google maps also use the magnetic compass or the direction of movement while driving/going. 

I don't think it is possible to get the orientation of the phone from gps, but if you know an app, which does that, i could take a look at it...

**Comment by jobbb** [comment]
https://play.google.com/store/apps/details?id=trackthisout_compass.com
