### ISSUE TITLE
Problems Phone without magnetic compass - map view

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#54]
Hy you told me:
...For phones without a magnetic compass there is the map view, where you can see the direction on the map.

I use map view. I can scroll to the city, but i cannot choose the city.
I type the name of the city but nothing happens. I cannot see the degrees and direction for praying.
Please give me a short guidance how it works.
Best regards

**Comment by metinkale38** [comment]
You have to enable GPS, otherwise it wont work

**Comment by jobbb** [comment]
I turned gps on, in the map view i see a blue point, i think this should my position and a blue line to the quibla. But the map says I'am in the ocean near Indonesia!?
I check this with osmand app (openstreetmap), the app shows my right position in the world.
So i think there is failure in your app. Please check it.
And if i turned on gps, i cannot type the name of my city. When do i need the feature to type the name of the city?
