### ISSUE TITLE
Suggestion: option to Stop Athan by turning the device screen face down

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#55]
I use this in app "salatuk". In some situation is it very helpful, if you forget to switch phone to silent or you are in a suddenly situation, where is it better to fastly stop Athan. You can set this as a option for check or uncheck, because some user want this, other users don't want this.

**Comment by metinkale38** [comment]
pressing the power button or swiping the notification will stop Athan.
you can do that faster than turning you phone and you won't do it by accident, like when turning the device screen down, so i think, thats enough...
