### ISSUE TITLE
Stop Athan by pressing power button not working without display-lock

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#59]
You told me:
..pressing the power button or swiping the notification will stop Athan.

But stop Athan by pressing power button is not working without display-lock.
Please test and correct the problem.
Best regards

**Comment by metinkale38** [comment]
if you have no display lock (=> you are using your phone), you can't intercept the powerbutton, it will turn the screen off! you normally don't want that. In this case you have to remove the notification.
