### ISSUE TITLE
Kıble pusulası bozulmuş

### ISSUE THREAD

**Issue by ilica18** [metinkale38/prayer-times-android#61]
Çalışmıyor

**Comment by metinkale38** [comment]
Sorunu tam olarak izah ederseniz, yardimci olmaya calisabilirim.

**Comment by ilica18** [comment]
selamun aleyküm sorunlar şunlar

   - kıble pusulası çalışmıyor sabit bi yeri gösteriyor
   - alarmı 10 dk kalaya ayarlıyorum uygulama 10 dk kaldı diye uyarı
   verdiğinde 6-7 dk kalmış oluyor
   - hadisleri indiriyorum eskiden yıldız koyduklarımda yıldız işareti
   kalırdı şimdi geriye bastığımda yıldız siliniyor ve 0 hadis bulundu hatası
   veriyor



şimdilik aklıma gelenler bunlar..

Saygılarımla
---
*Mesut ILICA*
*Web Master & Developer & Seo - Adwords Dijital Pazarlama Danışmanı*
mesut.ilica@gmail.com

2017-01-07 19:14 GMT+03:00 Metin Kale <notifications@github.com>:

**Comment by metinkale38** [comment]
- Sabit bir yeri göstermesi genellikle telefonun pusula özelliği olmaması demektir. Başka uygulama deneyebilirsiniz. 
- bazı telefon markaları (özellikle Samsung) şarj tüketimi azaltmak için alarmları geciktirebiliyor, şu anda bunu nasıl engelleyeceğimi (ve mümkün olup olmamasını) bilmiyorum.
- hadislere bakacağim inşallah
