### ISSUE TITLE
Newest versions not available in FDroid, only 3.6.1

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#62]
https://f-droid.org/wiki/page/com.metinkale.prayer
Build is failed. Please look for a solution.

Best regards

**Comment by est31** [comment]
Hi, I've seen the failure too. Sadly, I don't know how to fix it :/

**Comment by jobbb** [comment]
Hi,
In the build logs for version 3.6.2
https://f-droid.org/wiki/page/com.metinkale.prayer/lastbuild_167
and version 3.6.3:
https://f-droid.org/wiki/page/com.metinkale.prayer/lastbuild_171
you can see what is the problem.
But if you don't know to resolve it, here you find help:
https://f-droid.org/about/
quotation: ....you can also follow F-Droid’s microblog on identi.ca at fdroid@identi.ca, or discuss and get help on IRC in channel #fdroid on FreeNode. You can directly contact us by email at team@f-droid.org. If you want to help, you can join us.....

or in the forum.

Best regards

**Comment by jobbb** [comment]
Hi,
for problems you can also use the issue-tracker:
https://f-droid.org/issues/

Best regards

**Comment by jobbb** [comment]
I have noticed that Version 3.6.2 is available in Fdroid. And it has some features from version 3.6.3, like marocain prayer times, export to pdf/csv, option for OSM Geocoder as alternative.

Best regards
