### ISSUE TITLE
Silent Mode switched back to general profile, instead of last used profile

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#64]
If silent mode is activated after athan or early notification, after the silent time the silent mode switched back to general profile.
Is it possible that the silent mode switch back to the last used profile?

Best regards

**Comment by metinkale38** [comment]
Profiles are managed by the firmware of the manufacturer and are not a feature of stock Android. 

The Android SDK differentiates between normal, silent and vibrate. 

After silence mode, the correct (previous) mode is already selected.

**Comment by jobbb** [comment]
I understood, if my phone switched not back to the previous mode, it's a problem with the firmware not with your app.

**Comment by metinkale38** [comment]
No, if the mode does not switch back (normal, silent, vibrate) it is an app issue.

But if the profile (general, home, work, etc..) does not switch, it is a firmware issue/limitation.
