### ISSUE TITLE
marocain cityname (only habous.gov.ma) not displayed in app, something wrong

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#69]
1. i coosed a marocain city (habous.gov.ma) in your prayertime app. The cityname was displayed.
2. i updated the app to vers. 3.6.3
3. i searched for another marocain city. I choosed the marocain city(habous.gov.ma). After choosing, as a result the choosed city(habous.gov.ma) is displayed 3 times. One is displayed with the city name, the two other results are without name(only the name habous.gov.ma is displayed).
4. I choosed the city(habous.gov.ma) with name. The cityname was not displayed. (in the city overview i find the same city 3 times. One is displayed with name, the two other without name.
5. i deleted all cities in the app.
6. i search for my first marocain city (habous.gov.ma), i found the city and choosed it. As a result the choosed city(habous.gov.ma) is displayed 2 times, but all without names. I choosed one of them, but both are displayed without names.
7. reboot with the same result.
8. I added  a marocain city(diyanet.gov.tr) it's working. The problem is only with cities from habous.gov.ma
9. uninstall and new install the same result.
remark: if i delete the first unnamed city, the message "do you want to delete the city "null"? If i delete the first unnamed city. The second unnamed city is suddenly named as CSV Kenitra. I klicked on it, the city name is displayed, but all prayertimes are 00:00
---------------------reproducing the mistake------------------------------
10. i use a backup from other phone and then it's working.
11. after restore i have one marocain city(habous.gov.ma) in the app.
12. i add the second one(habous.gov.ma) and then the problem repeats. After adding the second city i see 2 new entries without display the cityname, i see only habous.gov.ma in the two entries.

Please can you solve the problem.
Best regards

**Comment by metinkale38** [comment]
will be fixed with the next update
