### ISSUE TITLE
Picker changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [metinkale38/prayer-times-android#76]
When I perform this sequence of events, the picker on screen loose the user input and go back to its default value

1. Open Side Drawer
2. Click on Makruh Time - Duration
3. Click on: 
a. Sunrise
b. Istiwa Time
c. Sunset
4. Pick a number different from default value
5.  Orientation Change

**Comment by metinkale38** [comment]
you cant change orientation on that screen

**Comment by reverse-unina** [comment]
I added the step 2 that leads to Settings activity which allows the orientation change.
I may add that the orientation change in the duration preference screen causes the app to return to the main settings screen. Is that a requisite?

Thank you for your time,
Vin

**Comment by metinkale38** [comment]
sorry, you are right, i thought you mean something else...

its a problem with the VNTNumberPickerPreference Library, i will create an issue there...
