### ISSUE TITLE
Alarmlar değişmiyor

### ISSUE THREAD

**Issue by ilica18** [metinkale38/prayer-times-android#80]
Sa başkan ezan alarmını değiştiriyorum bi süre sonra eski ayarlı olduğu vakite dönüyor

**Comment by metinkale38** [comment]
Aleyküm selam,

Ezan Bildirim ayarlari geri kapaniyor mu? Tam anlayamadim malesef...

**Comment by ilica18** [comment]
vakit bildirisi ayarında bir zaman ayarladıktan sonra (misal bir gün sonra)
bu ayarlanan dakikayı değiştirmeye kalktığımda uygulamadan çıktıktan bir
süre sonra veya ertesi günolduğunda 2. ayarladığım dk yerine daha önce
ayarlanan vakit geçerli oluyor kendi kendine

Saygılarımla
---
*Mesut ILICA*
*Web Master & Developer & Seo - Adwords Dijital Pazarlama Danışmanı*
mesut.ilica@gmail.com

2017-01-30 18:58 GMT+03:00 Metin Kale <notifications@github.com>:

**Comment by metinkale38** [comment]
gelecek güncelleme ile düzelmis olacaktir insallah...
