### ISSUE TITLE
morroco prayertime monthly view -question

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#83]
you wrote in my closed issue:
@metinkale38
Owner
metinkale38 commented Feb 1, 2017

the times are always downloaded for the next 2 month.
_______________________
Now it is the 05.02.2017, the monthly prayertimes are always still displayed till 28.02.2017. After this date the time is displayed as 00:00.
When is the next time, when the download begins for the next 2 month prayertimes?

Best regards

**Comment by metinkale38** [comment]
If you press refresh from the menu, it will be synced, otherwise it will just download the new times, if the data comes to the end...
