### ISSUE TITLE
Some Mystery

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#86]
Hy,

I choose a new prayersound and in the app i want hear the sound again. I click on the sound and then the sound is playing. But if the sound is playing and i turn the screenface, then the sound stops. The option "stop sound by turning the screen face down" is not activated.

Best regards

**Comment by metinkale38** [comment]
so you have the the option disabled, but it still stops?

**Comment by jobbb** [comment]
yes!

**Comment by metinkale38** [comment]
it seems, that the fdroid build failed
i will check it...

**Comment by jobbb** [comment]
yes, the fdroid build failed. https://f-droid.org/wiki/page/com.metinkale.prayer/lastbuild_181
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForFdroidRelease'.
> Job failed, see logs for details
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
