### ISSUE TITLE
Türkiye 

### ISSUE THREAD

**Issue by suaksoz** [metinkale38/prayer-times-android#87]
Diyanet, Türkiye için Türkçe karakterlere dönmüş herhalde. Türkiye'deki ü harfi bozuk gösteriyor. Bu yüzden, şehri otomatik bulma da düzgün çalışmıyor sanırım. 

Bilgine... 

![screenshot_20170306-003021](https://cloud.githubusercontent.com/assets/12976827/23591650/d90f34bc-0204-11e7-89b0-16cbbd211805.png)

**Comment by metinkale38** [comment]
Selamun aleyküm,

Diyanetin sayfasında öyle, güncellemeler de şehirleri güncellenmiştim...

Gelecek güncelleme ile düzeltirim inşallah...

Metin Kale

suaksoz <notifications@github.com> schrieb am So., 5. März 2017, 22:36:
