### ISSUE TITLE
morroco prayertimes - monthly view - not automaticly actualized

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#90]
Hi,
for my last question about morroco monthly view you wrote me:
...If you press refresh from the menu, it will be synced, otherwise it will just download the new times, if the data comes to the end...
I pressed refresh and it worked.

Also you wrote: ...otherwise it will just download the new times, if the data comes to the end...
I understand that your app will automatic download the new times, if the data comes to the end.

The morroco prayertimes are displayed till 30.03.2017.
At 01.04.2017 the morroco prayertimes dates are not automaticly actualized.
Please correct it for your next version. (i used your last fdroid version)

Best regards

**Comment by metinkale38** [comment]
should be fixed with #92
