### ISSUE TITLE
How to "show legacy widgets"? 

### ISSUE THREAD

**Issue by qwertyuser1983** [metinkale38/prayer-times-android#99]
I don't know why the widget not showing in my Advan i5e with Silverfish Launcher, but shown in Advan T1x+ with same Launcher. :)

So I want to try using Legacy Widgets, but the menu keeps grayed out. :)

**Comment by metinkale38** [comment]
If it is grayed out, you are already using the legacy widgets...

I implemented a new version of the widget (they look the same, but should work better) for newer android versions (> 7.0) but they are not compatible with older versions...
